services:
  rstudio:
    build:
      context: .
    container_name: reserch_env
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=rstudio
      - TZ=Asia/Tokyo
      - PYTHONUSERBASE=/home/rstudio/.pip
      - DISABLE_AUTH=true
      - ROOT=true
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio
    restart: unless-stopped