services:
  rstudio:
    build:
      context: .
    container_name: reserch_env
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=rstudio
      - TZ=Asia/Tokyo
      - PYTHONUSERBASE=/home/rstudio/.pip
      - DISABLE_AUTH=true
      - ROOT=true
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio
    restart: unless-stopped